# Generated by Django 5.2.4 on 2025-07-17 07:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
