# Generated by Django 5.2.4 on 2025-07-23 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_article_favorites',
                'indexes': [models.Index(fields=['article_id'], name='api_article_article_4d4326_idx'), models.Index(fields=['user_id'], name='api_article_user_id_84cf37_idx')],
                'unique_together': {('article_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_followers',
                'indexes': [models.Index(fields=['follower'], name='api_user_fo_followe_257b34_idx'), models.Index(fields=['followee'], name='api_user_fo_followe_d7dbec_idx')],
                'unique_together': {('follower', 'followee')},
            },
        ),
    ]
