### Create Artical
POST {{host}}/api/articles/
Accept: application/json
Content-Type: application/json

{
  "slug": "bai-7",
  "body": "helo world",
  "title": "BAI 1",
  "description": "this is a description",
  "author": "1",
  "tagList": [
    "tag1",
    "tag2"
  ]
}

### Artical get all
GET {{host}}/api/articles/
Accept: application/json
Content-Type: application/json


### Artical get by slug
GET {{host}}/api/articles/bai-10/
Accept: application/json
Content-Type: application/json



### Artical update by id
PUT {{host}}/api/articles/bai-10/
Accept: application/json
Content-Type: application/json

{
  "slug": "bai-10",
  "body": "helo world",
  "title": "BAI 1",
  "description": "this is a description",
  "author": "1",
  "tagList": [
    "tag1",
    "tag2"
  ]
}


### Artical delete by id
DELETE {{host}}/api/articles/bai-10/
Accept: application/json
Content-Type: application/json




