### Create Comment
POST {{host}}/api/articles/bai-1/comments/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "body": "comment bai 1",
  "author": "1"
}

### Get Comment by slug artical
GET {{host}}/api/articles/
Accept: application/json
Content-Type: application/json


### Delete comment by id
DELETE {{host}}/api/articles/bai-1/comments/1/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


