### Get follow list
GET {{host}}/api/follow/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Add follow, Unfollow
POST {{host}}/api/profiles/tamnx2/follow/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "tamnx2@gmial.com",
  "password": "123456",
  "username": "tamnx2"
}


